# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TShopMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for TShopMall
  
    pod 'AFNetworking','~> 4.0'
    pod 'YTKNetwork','~> 3.0.6'
    pod 'CYLTabBarController', '~> 1.29.0'
    pod 'CYLTabBarController/Lottie', '~> 1.29.0'  # 依赖Lottie库
    pod 'SDWebImage', '~> 5.11.1'
    pod 'Masonry','~>1.1.0'
    pod 'IQKeyboardManager', '~> 6.5.6'
    pod 'YYModel', '~> 1.0.4'
    pod 'YYCategories'
    pod 'MJRefresh', '~> 3.5.0'
    pod 'Toast', '~> 4.0.0'
    pod 'SDCycleScrollView', '~> 1.82'
    pod 'JXCategoryView', '~> 1.5.9'
    pod 'KVOController', '1.2.0'
    pod 'lottie-ios', '~> 2.5.3'
    pod 'GKNavigationBarViewController', '~> 3.0.2'
    pod 'WechatOpenSDK'
    pod 'SAMKeychain', '~> 1.5.3'
    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'NTESQuickPass'
    
  target 'TShopMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TShopMallUITests' do
    # Pods for testing
  end

end
